development:
  adapter: postgresql
  database: d3pd2giu4re8sr
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: d3pd2giu4re8sr
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: d3pd2giu4re8sr
  pool: 5
  timeout: 5000